site_name: reverb
repo_url: https://github.com/sarthhh/reverb
site_author: sarth
copyright: Copyright sarthhh ( 2023 - present )
site_url: https://sarthhh.github.io/reverb 

nav:
  - API Reference:
    - client: api_reference/client.md

theme:
  name: "material"
  font:
    text: Ubuntu

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - content.code.annotate
  palette:

    - scheme: light
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            merge_init_into_class: true
            inherited_members: true
          import:
            - https://docs.python.org/3.9/objects.inv
  - search
  - social:
      cards_color:
        fill: "#3761A3" 
        text: "#FFFFFF"


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details


extra:
  version: 0.0.4a
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sarthhh/reverb
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FyEE54u9GF